def create_post(title, content):
    response = requests.post(
        WP_URL,
        auth=HTTPBasicAuth(USERNAME, APP_PASSWORD),
        json={
            "title": title,
            "content": content,
            "status": "publish"  # or "draft"
        }
    )

    if response.status_code == 201:
        print("✅ Post created:", response.json()["link"])
    else:
        print("❌ Error:", response.text)


create_post(
    "My first agent post",
    "This was generated by my agent 🚀"
)